import 'package:sdb_trainer/src/model/exercisesdata.dart';

List<Exercises> extra_completely_new_Ex = [
  Exercises(
      goal: 0.0,
      name: '풀 리버스 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: "밀리터리 프레스",
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 힙 쓰러스트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 리버스 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 힙 쓰러스트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 풀 쓰루',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스 크런치(메디신 볼)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '알터네이팅 힐 터치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 니 힙 로테이션(메디신 볼)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 챱',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '행잉 레그 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '평행바 레그 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레그 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '크로스 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '크로스 크런치(메디신 볼)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 크로스 싯업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 트위스트 싯업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스 케이블 챱',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 메디신 볼 트위스트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '트렁크 로테이터',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프론트 플랭크(무릎)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프론트 플랭크(발가락)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '사이드 플랭크(무릎)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '사이드 플랭크(힙)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '사이드 플랭크(발가락)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'AB 사이클',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'AB 롤아웃(무릎)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'V-UP(메디신 볼)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'V-UP',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 니 싯업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 니 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '크런치',
      image: "assets/gif/Crunch_180.gif",
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '사이드 브릿지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 AB 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 싯업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 AB 크런치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '힐 터치',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 사이드 밴드',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싯업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '어시스티드 풀업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '클로즈그립 랫 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'V바 랫 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인버티드 풀업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '랫 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '풀업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머슬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '친업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스그립 랫 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스그립 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'V바 풀업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '와이드그립 랫 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 스트레이트 암 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 얼터네이팅 덤벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 바벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'T바 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '펜들레이 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 덤벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 해머 덤벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 롱 바벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 리버스그립 바벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 싱글 암 롱 바벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스 인클라인 덤벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '로프 케이블 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 덤벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 케이블 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 케이블 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 덤벨 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 랫 풀다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스탠딩 케이블 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 로우 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 하이 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: ' 얼터네이팅 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: ' 얼터네이팅 해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스탠딩 싱글암 케이블 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 슈러그',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 슈러그',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 컬',
      image: "assets/gif/Barbell-Curl_Upper-Arms_1080.webp",
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '컨센트레이션 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '크로스 바디 해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'EZ바 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 얼터네이팅 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 얼터네이팅 해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 컬(무릎)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 하이 케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 더블 바이셉스 케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 로프 케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프리쳐 바벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프리쳐 케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프리쳐 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프리쳐 EZ바 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프리쳐 해머 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프리쳐 싱글 암 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '로프 케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 얼터네이팅 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 얼터네이팅 해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 케이블 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 덤벨 컬(인클라인 벤치)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 스파이더 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 스파이더 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 카프 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '카프 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스탠딩 카프 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 카프 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 카프 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 덤벨 카프 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스미스 카프 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 카프 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 싱글-레그 카프 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '얼터네이팅 덤벨 바벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 바벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '체스트 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 체스트 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 체스트 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 스미스 머신 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 푸쉬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '엘레베이티드 푸쉬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 얼터네이팅 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 바벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 해머 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 싱글 암 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 스미스 머신 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 트위스팅 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '푸쉬업(무릎)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '크로스오버 푸쉬업(메디신 볼)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '푸쉬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스미스 머신 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '트위스팅 덤벨 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '와이드그립 푸쉬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '클로즈그립 푸쉬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 크로스오버',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤치 푸쉬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 덤벨 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '하이 케이블 크로스 오버',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 케이블 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 덤벨 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 트위스팅 덤벨 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '로우 케이블 크로스 오버',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 풀오버',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '체스트 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 니 싱글 레그 힙 리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '힙 리프트(발높여서)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 힙 리프트(발높여서)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '힙 리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 힙 리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 데드리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근", "허리", "등"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 루마니안 데드리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근", "허리", "등"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 스티프 레그 데드리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근", "허리", "등"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 스모 데드리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근", "허리", "등"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스미스 머신 데드리프트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근", "허리", "등"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레그 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 알터네이팅 레그 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 레그 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 싱글 레그 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 레그 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 대각선 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 핵 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 프론트 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 리버스 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 사이드 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 스플릿 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 스텝 업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 워킹 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '대각선 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 대각선 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 리버스 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 사이드 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 스플릿 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 스텝 업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 워킹 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '포워드 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레터럴 바벨 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레터럴 바벨 스텝 업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레터럴 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레터럴 스텝 업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레그 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '파워 레그 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 머신 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 핵 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 바벨 사이드 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 덤벨 사이드 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 바벨 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 박스 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 덤벨 박스 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 덤벨 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스미스 머신 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스플릿 스쿼트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스텝 업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '워킹 런지',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리", "둔근"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '알터네이팅 레그 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '레그 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 레그 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["다리"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '알터네이팅 슈퍼맨',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["허리"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '백 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["허리"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '슈퍼맨',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["허리"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '슈퍼맨 홀드',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["허리"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '아놀드 덤벨 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 숄더 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 얼터네디팅 숄더 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 업라이트 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 업라이트 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 업라이트 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 숄더 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 숄더 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 덤벨 숄더 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스미스 머신 숄더 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 프론트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 케이블 리어 델트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤트 오버 덤벨 리어 델트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 프론트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 래터럴 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 사이드 래터럴 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 프론트 래터럴 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '프론트 플레이트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "원판",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 덤벨 익스터널 로테이션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 덤벨 리어 델트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 싱글 암 덤벨 리어 델트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리어 델트 플라이',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 덤벨 리어 델트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '시티드 덤벨 리어 델트 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 케이블 래터럴 레이즈',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 익스터널 로테이션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '클로즈그립 벤치 프레스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 로프 페이스 풀',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["어깨"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '어시스티드 딥스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '벤치 딥스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '다이아몬드 푸쉬업',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '딥스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "맨몸",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 딥스',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["가슴", "삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 덤벨 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '디클라인 EZ바 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '덤벨 킥 백',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '인클라인 EZ바 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '케이블 트라이셉스 익스텐션(무릎)',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리닝 오버헤드 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 케이블 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 EZ바 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 싱글 덤벨 트라이셉 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 싱글 암 덤벨 트라이셉 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '라잉 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 덤벨 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 EZ바 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 로프 케이블 트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 싱글 덤벨 트라이셉 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 싱글 암 케이블 트라이셉 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '오버헤드 싱글 암 덤벨 트라이셉 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '리버스 트라이셉스 푸쉬다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '로프 트라이셉스 푸쉬다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '싱글 암 트라이셉 푸쉬다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '트라이셉스 익스텐션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '트라이셉스 푸쉬다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: 'V바 트라이셉스 푸쉬다운',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["삼두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '힙 어브덕션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '힙 어뎍션',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["둔근"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '바벨 힙 쓰러스트',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["둔근"],
      category: "바벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '러닝',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["유산소"],
      category: "유산소",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '사이클링',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["유산소"],
      category: "유산소",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '플랭크',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["복근"],
      category: "유산소",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '스텝 머신',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["유산소"],
      category: "유산소",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '로잉',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["유산소"],
      category: "유산소",
      note: '')
];
