import 'package:sdb_trainer/src/model/exercisesdata.dart';

List<Exercises> new_Ex = [
  Exercises(
      goal: 0.0,
      name: '머신 로우 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: '머신 하이 로우',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["등", "이두"],
      category: "머신",
      note: ''),
  Exercises(
      goal: 0.0,
      name: ' 얼터네이팅 덤벨 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
  Exercises(
      goal: 0.0,
      name: ' 얼터네이팅 해머 컬',
      image: null,
      onerm: 0.0,
      custom: false,
      target: ["이두"],
      category: "덤벨",
      note: ''),
];

List<String> delete_Ex = [
  '원 암 덤벨 로우',
  '시티드 로우',
  '바이셉스 컬',
  '바텀 하프 컬',
  '탑 하프 컬',
  '라잉 더블 바이셉스 케이블 컬',
  '로프 케이블 해머 컬',
  '싱글 암 바벨 컬',
  '시티드 카프 레이즈',
  '플랫 벤치 프레스',
  '머신 버티컬 벤치 프레스',
  '덤벨 트위스팅 숄더 프레스',
  '시티드 덤벨 리어 델트 엘보우 레이즈',
  '싱글 암 케이블 리어 델트 레이즈(무릎)',
  '포워드 린 딥스',
  '디클라인 싱글 덤벨 트라이셉스 익스텐션',
  '디클라인 싱글 암 덤벨 트라이셉스 익스텐션',
  '로우 케이블 트라이셉스 익스텐션',
  '라잉 오버헤드 EZ바 트라이셉스 익스텐션',
  '라잉 리버스 EZ바 트라이셉스 익스텐션',
  '싱글 암 타월 트라이셉 푸쉬다운',
  '타월 트라이셉스 푸쉬다운',
];
